name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - run: ./gradlew lint --stacktrace
      - run: ./gradlew spotlessApply --stacktrace

      - name: Run git push
      - run: |
          git config --global user.email "bot@therealsuji.tk"
          git config --global user.name "earphone-jack"
          git add --all
          git commit -m "Format files from commit $GITHUB_SHA" || true
          git push
